### ISSUE TITLE
메일 드렸던 사람입니다.

### ISSUE THREAD

**Issue by Koobonik** [JosephNK/SwiftyIamport#2]
klassmall 이라는 쇼핑몰앱인데

viewDidLoad 안에다가 
IAMPortPay.sharedInstance.configure(scheme: "klassmall")  // info.plist에 설정한 scheme
        IAMPortPay.sharedInstance
            //.setWebView(self.WebView)   // 현재 Controller에 있는 WebView 지정
            .setRedirectUrl("klassmall")        // m_redirect_url 주소
이런식으로 설정해주었습니다.

info.plist 는
<key>CFBundleURLSchemes</key>
	<array>
		<string>klassmall</string>
	</array>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>pwmw.klassmall</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>klassmall</string>
			</array>
		</dict>
		<dict/>
	</array>

작성하였습니다.

ISP 결제하고오면 사파리가 열리는데 어디를 잘못한걸까요 ㅠㅠ 
소스가 필요하시면 프로젝트 통째로 드리겠습니다.. 며칠째 고생중이네요

메일 답변 감사드렸습니다!!

**Comment by JosephNK** [comment]
setRedirectUrl 이 부분에 url이 아닌데... 사용하시는게 아니라면 지워보세요. 아니면 리다이렉션 하는 url이 있으면 넣으시구요.
그리고 AppDelegate 부분에도 README 파일에 있는거 적용하신건가요?

**Comment by Koobonik** [comment]
> setRedirectUrl 이 부분에 url이 아닌데... 사용하시는게 아니라면 지워보세요. 아니면 리다이렉션 하는 url이 있으면 넣으시구요.
> 그리고 AppDelegate 부분에도 README 파일에 있는거 적용하신건가요?

AppDelegate 은 README에 있는것 적용했습니다. 
setRedirectUrl 부분은 지워도 사파리 열리는건 똑같네요 흠...

**Comment by JosephNK** [comment]
@Koobonik 
SwiftyIamport DEMO 앱으로 한번 해보셨나요? 
지금 DEMO앱으로 ISP 결제 해봤는데... 잘 작동 하네요.
일단 SwiftyIamport DEMO 앱으로 해보시고, 된다면 똑같이 한번 해보세요~
그래도 안되면, AppDelegate 파일과 위에 적어 놓으신 Controller 파일을 한번 봐야할 듯 해요.
그리고 WKWebView를 사용하신다고 하셨는데.. 
아마 WKWebView는 setWebView가 안되실꺼예요. :(
UIWebView로 사용해주세요~

**Comment by JosephNK** [comment]
@Koobonik 
별 다른 얘기가 없어서 이슈를 닫도록 할께요..
아 그리고 WKWebView도 지원 되게 업데이트 했어요. :)
